spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/pagination
    password: Password@1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
